<a href="https://colab.research.google.com/github/sergio1/estudos/blob/main/aula_6_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Exemplo 1: Criando um array a partir de uma lista Python
# Este array unidimensional representa um vetor simples.
arr1 = np.array([1, 2, 3, 4, 5])
print("Array criado a partir de uma lista:", arr1)
# Saída esperada: Array criado a partir de uma lista: [1 2 3 4 5]

# Exemplo 2: Criando um array a partir de uma tupla Python
# Tuplas também podem ser usadas para inicializar arrays, demonstrando a flexibilidade do np.array().
arr2 = np.array((10, 20, 30, 40, 50))
print("Array criado a partir de uma tupla:", arr2)
# Saída esperada: Array criado a partir de uma tupla: [10 20 30 40 50]

Array criado a partir de uma lista: [1 2 3 4 5]
Array criado a partir de uma tupla: [10 20 30 40 50]


In [ ]:
import numpy as np

# Exemplo 3: Criando uma matriz 2x3 (2 linhas e 3 colunas)
# Esta matriz pode representar, por exemplo, dados de duas amostras com três características cada.
mat1 = np.array([[1, 2, 3], [4, 5, 6]])
print("\nMatriz 2x3:\n", mat1)
# Saída esperada:
# Matriz 2x3:
# [[1 2 3]
#  [4 5 6]]

# Exemplo 4: Criando uma matriz 3x2 (3 linhas e 2 colunas)
# Útil para representar relações ou transformações em espaços bidimensionais.
mat2 = np.array([[10, 20], [30, 40], [50, 60]])
print("\nMatriz 3x2:\n", mat2)
# Saída esperada:
# Matriz 3x2:
# [[10 20]
#  [30 40]
#  [50 60]]


Matriz 2x3:
 [[1 2 3]
 [4 5 6]]

Matriz 3x2:
 [[10 20]
 [30 40]
 [50 60]]


In [ ]:
import numpy as np

# Definindo dois arrays para demonstração das operações
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Soma de arrays: Cada elemento de arr1 é somado ao elemento correspondente de arr2.
# Resultado: [1+4, 2+5, 3+6] = [5, 7, 9]
soma = arr1 + arr2
print("Soma dos arrays:", soma)
# Saída esperada: Soma dos arrays: [5 7 9]

# Multiplicação de arrays: Cada elemento de arr1 é multiplicado pelo elemento correspondente de arr2.
# Resultado: [1*4, 2*5, 3*6] = [4, 10, 18]
multiplicacao = arr1 * arr2
print("Multiplicação dos arrays (elemento a elemento):", multiplicacao)
# Saída esperada: Multiplicação dos arrays (elemento a elemento): [ 4 10 18]

# Divisão de arrays: Cada elemento de arr2 é dividido pelo elemento correspondente de arr1.
# Resultado: [4/1, 5/2, 6/3] = [4. , 2.5, 2. ]
divisao = arr2 / arr1
print("Divisão dos arrays (elemento a elemento):", divisao)
# Saída esperada: Divisão dos arrays (elemento a elemento): [4.  2.5 2. ]

Soma dos arrays: [5 7 9]
Multiplicação dos arrays (elemento a elemento): [ 4 10 18]
Divisão dos arrays (elemento a elemento): [4.  2.5 2. ]


In [ ]:
import numpy as np

# Criando um array de exemplo para aplicar as funções matemáticas
arr = np.array([1, 2, 3, 4, 5])
print("Array original:", arr)

# Raiz quadrada de cada elemento: np.sqrt()
# Calcula a raiz quadrada de cada número no array.
raiz_quadrada = np.sqrt(arr)
print("Raiz quadrada de cada elemento:", raiz_quadrada)
# Saída esperada: Raiz quadrada de cada elemento: [1.         1.41421356 1.73205081 2.         2.23606798]

# Seno de cada elemento: np.sin()
# Calcula o seno (em radianos) de cada número no array.
seno = np.sin(arr)
print("Seno de cada elemento:", seno)
# Saída esperada: Seno de cada elemento: [0.84147098 0.90929743 0.14112001 -0.7568025  -0.95892427]

# Logaritmo natural de cada elemento: np.log()
# Calcula o logaritmo natural (base e) de cada número no array.
logaritmo = np.log(arr)
print("Logaritmo natural de cada elemento:", logaritmo)
# Saída esperada: Logaritmo natural de cada elemento: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Acessando o primeiro elemento (índice 0)
print("Primeiro elemento do array:", arr[0])
# Saída esperada: Primeiro elemento do array: 10

# Acessando o último elemento (índice -1)
print("Último elemento do array:", arr[-1])
# Saída esperada: Último elemento do array: 50


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Fatiando do segundo ao quarto elemento (índices 1 a 3)
print("Elementos do índice 1 ao 3 (exclusive):", arr[1:4])
# Saída esperada: Elementos do índice 1 ao 3 (exclusive): [20 30 40]

# Fatiando do início até o terceiro elemento (índice 2 exclusive)
print("Elementos do início ao índice 2 (exclusive):", arr[:3])
# Saída esperada: Elementos do início ao índice 2 (exclusive): [10 20 30]

# Fatiando do terceiro elemento (índice 2) até o final
print("Elementos do índice 2 ao final:", arr[2:])
# Saída esperada: Elementos do índice 2 ao final: [30 40 50]

# Fatiamento com passo (a cada 2 elementos)
print("Elementos com passo de 2:", arr[::2])
# Saída esperada: Elementos com passo de 2: [10 30 50]

In [ ]:
import numpy as np

mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\nMatriz original:\n", mat)
# Saída esperada:
# Matriz original:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

# Acessando um elemento específico: linha 0, coluna 1 (valor 2)
print("Elemento na linha 0, coluna 1:", mat[0, 1])
# Saída esperada: Elemento na linha 0, coluna 1: 2

# Acessando todos os elementos da coluna 2 (valores 3, 6, 9)
# O `:` indica que todas as linhas devem ser consideradas para a coluna especificada.
print("Todos os elementos da coluna 2:", mat[:, 2])
# Saída esperada: Todos os elementos da coluna 2: [3 6 9]

# Acessando todos os elementos da linha 1 (valores 4, 5, 6)
print("Todos os elementos da linha 1:", mat[1, :])
# Saída esperada: Todos os elementos da linha 1: [4 5 6]

# Fatiando uma submatriz: linhas 0 e 1, colunas 0 e 1 (valores [[1, 2], [4, 5]])
print("Submatriz (linhas 0-1, colunas 0-1):\n", mat[0:2, 0:2])
# Saída esperada:
# Submatriz (linhas 0-1, colunas 0-1):
# [[1 2]
#  [4 5]]

In [ ]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
c = a * b
print(c)

[10 40 90]


In [ ]:
dados = np.array([5.5, 6.0, 6.3, 5.9])
media = np.mean(dados)
desvio = np.std(dados)


In [ ]:
sensores = np.array([[10, 20, 30], [15, 22, 29]])
correlacao = np.corrcoef(sensores)
print(correlacao)

[[1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np

dados_pressao = np.array([5.2, 5.5, 5.8, 5.3])
media = np.mean(dados_pressao)
desvio = np.std(dados_pressao)

print("Média da pressão:", media)
print("Desvio padrão:", desvio)

Média da pressão: 5.45
Desvio padrão: 0.2291287847477919


In [ ]:
import numpy as np
a = np.array([3, 6, 9])
b = np.array([1, 2, 3])
c = a * b
print(c)  # [3 12 27]

[ 3 12 27]
